// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3glEp2zRucPYEHKhoeTMg6LYvNNUvQdA',
    appId: '1:1027814062766:web:d66429cd18eb0825fc4b3f',
    messagingSenderId: '1027814062766',
    projectId: 'note-app-c6af3',
    authDomain: 'note-app-c6af3.firebaseapp.com',
    storageBucket: 'note-app-c6af3.firebasestorage.app',
    measurementId: 'G-84E2FRDXWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPTj-i8sUYmAdBZY7hxTJRdnZqLjekofs',
    appId: '1:1027814062766:android:6b83800006f9ac91fc4b3f',
    messagingSenderId: '1027814062766',
    projectId: 'note-app-c6af3',
    storageBucket: 'note-app-c6af3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQLLFhbQYJYPtoYKjBwbtLEW3G8T1rLec',
    appId: '1:1027814062766:ios:c2f0cdffc32f9a3ffc4b3f',
    messagingSenderId: '1027814062766',
    projectId: 'note-app-c6af3',
    storageBucket: 'note-app-c6af3.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQLLFhbQYJYPtoYKjBwbtLEW3G8T1rLec',
    appId: '1:1027814062766:ios:c2f0cdffc32f9a3ffc4b3f',
    messagingSenderId: '1027814062766',
    projectId: 'note-app-c6af3',
    storageBucket: 'note-app-c6af3.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3glEp2zRucPYEHKhoeTMg6LYvNNUvQdA',
    appId: '1:1027814062766:web:5fefc3c1b9a3997afc4b3f',
    messagingSenderId: '1027814062766',
    projectId: 'note-app-c6af3',
    authDomain: 'note-app-c6af3.firebaseapp.com',
    storageBucket: 'note-app-c6af3.firebasestorage.app',
    measurementId: 'G-06QLSLHJQZ',
  );
}
